openapi: "3.0.0"
info:
  title: 情報管理システム
  version: 1.0.0
servers:
  - url: "http://localhost:8002"
tags:
  - name: top
    description: トップページで必要になる情報をまとめて管理
  - name: task
    description: タスク管理
paths:
  /top:
    get:
      description: 本日以前が対象となる情報の概要を取得する
      tags:
        - top
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Top"
components:
  schemas:
    ShortTask:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        target_date:
          type: string
    ShortSchedule:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        start_datetime:
          type: string
        end_datetime:
          type: string
    ShortMuscleTrainingHistory:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        count:
          type: integer
          format: int32
        created_at:
          type: string
    Top:
      type: object
      properties:
        tasks:
          type: array
          items:
            $ref: "#/components/schemas/ShortTask"
          example:
            - id: 1
              name: 読書
              target_date: '2025-03-21'
        schedules:
          type: array
          items:
            $ref: "#/components/schemas/ShortSchedule"
          example:
            - id: 1
              name: ゴミ捨て
              start_datetime: '2025-03-21 09:00:00'
              end_datetime: '2025-03-21 09:00:00'
            - id: 2
              name: バイオリンレッスン
              start_datetime: '2021-03-16 15:00:00'
              end_datetime: '2025-07-23 16:00:00'
        muscle_training_histories:
          type: array
          items:
            $ref: "#/components/schemas/ShortMuscleTrainingHistory"
          example:
            - id: 1
              name: ゴミ捨て
              count: 15
              created_at: '2025-03-21 03:44:25'
    NotFound:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: コンテンツがありません。
    UnprocessableEntityAboutName:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: "'name'は必須項目です。"
    UnprocessableEntityAboutIsDone:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: "'is_done'は必須項目です。"
    InternalServerError:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: 予期せぬエラーが発生しました。
